### ISSUE TITLE
Job AWS console link broken

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/rsv#53]
### Current Behavior

The URL behind the "AWS Batch Console" link in the run-build summary ([e.g.](https://github.com/nextstrain/rsv/actions/runs/7630582217)) is broken as it contains `region=***`. This is probably a misconfiguration in how we're using the pathogen-repo-build workflow.

I can fix this next week, just noting it here.

**Comment by tsibley** [comment]
That looks like `AWS_REGION` is being passed as a secret, so its value is being masked in the logs by GitHub Actions.

**Comment by tsibley** [comment]
(This is a reason not to use secrets for non-secret things if you can help it.)

**Comment by joverlee521** [comment]
Ah, I forgot to remove the `AWS_DEFAULT_REGION` secret after I [removed references to it in the GH Action workflows](https://github.com/nextstrain/rsv/commit/77a5f8725f29f44762877e202e36d2c21f0066ea). 

I've deleted the secret from this repo. If we need to set the value for any reason in the future, we should use the non-secret [GH Action variables](https://docs.github.com/en/actions/learn-github-actions/variables).

**Comment by jameshadfield** [comment]
Thanks for fixing Jover. For anyone else who wants to understand _why_ this happened:

* The reusable action [hardcodes "region=us-east-1"](https://github.com/nextstrain/.github/blob/05a227bb20d245aa30a9a9f945eb94b0591d31bc/text-templates/attach-aws-batch.md?plain=1#L14) in the URL. The action never uses `AWS_DEFAULT_REGION`.
* The RSV repo had a repo-level secret `AWS_DEFAULT_REGION="us-east-1"`
* GitHub will automagically ["mask any secrets that might have been added accidentally"](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) to the `GITHUB_STEP_SUMMARY`
